apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk152-linux-kubectl
  namespace: class-5
  labels:
    app: sk152-linux-kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk152-linux-kubectl
  template:
    metadata:
      labels:
        app: sk152-linux-kubectl
    spec:
      containers:
        - name: linux
          image: skala-registry.skala-ai.com/sk152-linux-kubectl:1.0
          imagePullPolicy: Always
          env:
            - name: KUBECONFIG
              value: /root/.kube/config
          volumeMounts:
            - name: kubeconfig
              mountPath: /root/.kube
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: kubeconfig
          configMap:
            name: sk152-linux-kubeconfig
            defaultMode: 0600
