apiVersion: v1
kind: Pod
metadata:
  name: sk152-pvc-handler-pod
  namespace: class-5
spec:
  containers:
  - name: ubuntu
    image: ubuntu:22.04
    command: ["/bin/bash","-lc","apt-get update && apt-get install -y vim sudo && tail -f /dev/null"]
    volumeMounts:
    - name: efs-config
      mountPath: /config
  volumes:
  - name: efs-config
    persistentVolumeClaim:
      claimName: sk152-efs-sc-myfirst-api-server-pvc
