apiVersion: v1
data:
  config: |
    apiVersion: v1
    kind: Config
    clusters:
    - name: skala-2026
      cluster:
        server: https://F6CF0573B26EB0F515847B76DBFD3019.gr7.ap-northeast-2.eks.amazonaws.com
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJRExvS21IUTFyekF3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBM016RXdOREl4TXpOYUZ3MHpOakEzTWpnd05ESTJNek5hTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUN1bVVrWS83YU9FcGF2Tm9PZVg0WWd3Wk9ZSHFUV01ieTgvOG9ORVJwRGFhQSs5QlU2QXd6YUh5OTQKMTF6SlAwQklCNERydW5vOFJrcTFIOUZueFRPSlN0cmhweThTK3JJTmkvUmovSmhBSm1FVktyMzNvUU5OVVYxMgpmRUt5RHJ4SXVzSjVWUXk0MmdtWDBCeW5pam03SDgzRXlCajlLSm5lbDRhbnJEQ1ZDbUo5K3I2RW1ZdE9qVjl1CmVQOUVrSytQeXh6cW9TZ0xqcmpvTWhnbDc1aXR0aXc0SzFkTmxCaVdKaE5WM0o5VVk2dFgzOURTSEJHZXVlNlYKMTl4cmxiQjR6Yi9iQkRpWUR5bVRWTi9WNFVkWUJyZGg3b2g3VzE0bC8xVTNKL3l1MmVNYkcwMUVJVGhldjdmQwpHQlYrbE9IWEcxdXpFRnZtbW8xT0UyeUJmTE5CQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTTDVjN1pheWtoWERVOUY5elRxQjRIVjdMbzFUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQTBETWlQWVlIVwpuTW5MbjNqU0QxMnMvRVdrbzVWM0xMckpoQnAyb05pSTVpUyt3TEZoeUk4djZGaGExamgwMkZ5Vm9KNlMxU0dXCjd6T1l2M2R5VU9hdnc3a2ZxSnpHcjlPY0V4Y0p1LzdDZnowZ202Rkx2YTI3TmlwVkdoM2UwaGVwcEwvVUFoRVEKZFBQNEd0dm1za1dIMk1vdExHQzQwTjlRZDZSVGJxVm9hbXhQSVNrRjBNeWE1dVVwald2TWx0RWJNMjNlR1lqVQpuWi8xZ01OWUVKZXQxSFJNV2tlUGlETFBiTHV2NUhNcU9hSDBpY3Z2QkRtaDB5Q3pCaDI1MUN5V0VZUTV0blNJCnNHTDd3YVNMM3dSbHh0bEorRHV0S2IrTW56YStVWUpSRkdLVVgrVkVtQllZNFB5WWRBZjNmL2YwakVucjBJZmoKMHkvT1lkajZQTGkvCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    contexts:
    - name: skala-admin-sa@class-5
      context:
        cluster: skala-2026
        namespace: class-5
        user: skala-admin-sa
    current-context: skala-admin-sa@class-5
    users:
    - name: skala-admin-sa
      user:
        token: eyJhbGciOiJSUzI1NiIsImtpZCI6Imx3Zk55ZzZuMld1VDg0LUV1OTdqaXRNS2pHd3JSdEFMNjYwZURicnBnODAifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJjbGFzcy01Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InNrYWxhLWFkbWluLXNhLXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InNrYWxhLWFkbWluLXNhIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNWY0NjZkYTItN2QyMS00N2Q3LTljZGUtOTc2ZmFhZTk0NGIzIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmNsYXNzLTU6c2thbGEtYWRtaW4tc2EifQ.GQpp2kOemEr96LaDc8TCax7DJblgLqTe_RNvsdAA-rp09grGBtFclMl6A2kI5jDCDUg9uV7F8b3z7pA6OknHtHJrVsw-vvYvFjqu-_f9YEwMfW-P4egi1USUK3HBwyHa0ORrsYixvzpGM9yeywRi290pFSwaFXGzjC0j8iQ5a5FK8rsU7MMG1SXuxlRemQZscPdREn9RX8hP8VmTgNy-rfa_iVK0XDm4grTcrvSrK8mSzs3ENTL762V4l5FE75ruuQxZrMahXV8PkJpJil3UBJyzCj_KD1TNOBO30SfuVGeRAe7lIZf_KZJ_0jceAp1SbT0s5enq85zVWM_P4FUqWg
kind: ConfigMap
metadata:
  name: skala-ubuntu-kubeconfig
