apiVersion: v1
kind: Pod
metadata:
  name: sk152-ubuntu-kubectl
  namespace: class-5
  labels:
    app: sk152-ubuntu-kubectl
spec:
  containers:
    - name: linux
      image: skala-registry.skala-ai.com/library/skala-ubuntu-kubectl:1.0
      imagePullPolicy: Always
      env:
        - name: KUBECONFIG
          value: /root/.kube/config
      volumeMounts:
        - name: kubeconfig
          mountPath: /root/.kube
          readOnly: true
  volumes:
    - name: kubeconfig
      configMap:
        name: skala-ubuntu-kubeconfig
        defaultMode: 0600
